packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false # telemetria de dependência (swagger-ui-dist)
  '@swc/core': true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: true
  cpu-features: false
  protobufjs: false
  ssh2: false
